fix(test): should work now

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -22,6 +22,8 @@ jobs:
         os: [ ubuntu-latest ]
         node-version: [ 14.x ]
         browser: [ chromium ]
+    outputs:
+      output1: ${{ steps.final-check1.outputs.test-status }}
     steps:
         
       - name: 'Run e2e tests (chromium)'
@@ -51,7 +53,9 @@ jobs:
 
       - name: Bypass failure if test didn't run
         if: ${{ always() && (steps.cypress-tests-react.outcome == 'failure') && (steps.cypress-tests-react.outputs.dashboardUrl == '') }}
-        run: exit 1
+        run: |
+          echo "::set-output name=test-status::failed"
+          exit 1
 
       - name: Fail job if a test failed
         if: ${{ always() && (steps.cypress-tests-react.outcome == 'failure') && (steps.cypress-tests-react.outputs.dashboardUrl != '') }}
@@ -64,7 +68,7 @@ jobs:
     needs: react-tests
     steps:
       - name: sadasds
-        run: echo ${{ needs.react-tests.result }}
+        run: echo ${{ needs.react-tests.outputs.output1 }}
       - name: Check React test matrix status
-        if: "${{ needs.react-tests.result == 'success' }}"
+        if: "${{ needs.react-tests.outputs.output1 == 'failed' }}"
         run: exit 1
